[package]
name = "raid-race-lib"
version.workspace = true
edition.workspace = true

[features]
server = []

[dependencies]
bitflags = "2.13.1"
avian3d.workspace = true
bevy.workspace = true
hakari = { version = "0.1", path = "../hakari" }
lightyear.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
bevy_enhanced_input = "0.26.0"

[lints]
workspace = true
