[package]
name = "raid-race-lib"
version.workspace = true
edition.workspace = true

[features]
server = []
client = []

[dependencies]
naia-bevy-shared = { git = "https://github.com/getong/naia", branch = "bevy-0.19" }
bitflags = "2.13.1"
avian3d.workspace = true
bevy.workspace = true
typed-builder = "0.23.2"
hakari = { version = "0.1", path = "../hakari" }

[lints]
workspace = true
