[package]
name = "raid-race"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", default-features = false, features = [
	"3d_bevy_render",
	"default_app",
	"default_platform",
	"dynamic_linking",
	"scene",
	"audio",
	"debug",
] }
avian3d = { version = "0.7.0", default-features = false, features = [
	"3d",
	"bevy_scene",
	"collider-from-mesh",
	"debug-plugin",
	"f64",
	"parallel",
	"parry-f64",
	"xpbd_joints",
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
