[workspace]
metadata.crane.name = "raid-race"
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
raid-race-lib = { path = "crates/lib", version = "0.1.0" }
tracing = "0.1.44"
bevy = { version = "0.19.0", default-features = false, features = [
	"bevy_asset",
	"bevy_color",
	"bevy_mesh",
	"bevy_pbr",
	"bevy_scene",
	"debug",
] }
avian3d = { version = "0.7.0", default-features = false, features = [
	"3d",
	"f64",
	"parallel",
	"parry-f64",
	"xpbd_joints",
] }
lightyear = { version = "0.29.0", default-features = false, features = [
	"replication",
	"avian3d",
	"webtransport",
	"netcode",
	"input_bei",
] }
futures = { version = "0.3.34", default-features = false }
async-net = "2.0.0"
async-h1 = "2.3.4"
http-types = "2.12.0"
serde = { version = "1.0.229", features = ["derive"] }
either = { version = "1.18.0", features = ["serde"] }
rand = "0.10.2"

[workspace.lints.clippy]
unwrap_used = "deny"
type_complexity = "allow"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
