[package]
name = "raid-race-server"
version.workspace = true
edition.workspace = true

[dependencies]
raid-race-lib.workspace = true
bevy.workspace = true
avian3d.workspace = true
tracing.workspace = true
typed-builder = "0.23.2"
hakari = { version = "0.1", path = "../hakari" }
lightyear = { workspace = true, features = [
	"server",
	"webtransport_self_signed",
] }
async-channel = "2.5.0"
async-lock = "3.4.2"
rand.workspace = true
wtransport = "0.6.1"
clap = { version = "4.6.6", features = ["derive"] }
async-h1.workspace = true
async-net.workspace = true
http-types.workspace = true
serde.workspace = true
rustyline = { version = "18.0.1", default-features = false }

[lints]
workspace = true
