[package]
name = "raid-race-server"
version.workspace = true
edition.workspace = true

[dependencies]
raid-race-lib = { workspace = true, features = ["server"] }
bevy.workspace = true
avian3d.workspace = true
tracing.workspace = true
typed-builder = "0.23.2"
hakari = { version = "0.1", path = "../hakari" }
lightyear = { workspace = true, features = [
	"server",
	"webtransport_self_signed",
] }
async-channel = "2.5.0"
async-lock = "3.4.2"
async-net.workspace = true
rand = "0.10.2"
wtransport = "0.6.1"

[build-dependencies]
wtransport = "0.6.1"

[lints]
workspace = true
