[package]
name = "raid-race"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = ["3d", "audio", "dynamic_linking", "ui"] }
avian3d = { workspace = true, features = ["debug-plugin"] }
tracing = "0.1.44"
raid-race-lib.workspace = true
hakari = { version = "0.1", path = "../hakari" }
lightyear = { workspace = true, features = [
	"client",
	"prediction",
	"interpolation",
] }
futures.workspace = true
async-net.workspace = true
async-h1.workspace = true
http-types.workspace = true

# TODO: use crates.io when these get merged and released
bevy-inspector-egui = { git = "https://github.com/kisya-games/bevy-inspector-egui", branch = "egui-0.36" }
bevy_console = { git = "https://github.com/justdeeevin/bevy-console", branch = "bevy_egui_0.42" }

[lints]
workspace = true
